In [15]:
import glob
import pandas as pd

# Use r'' for raw string to handle Windows backslashes properly
path = r'C:/Data Analytics/Bike/*.csv'
file_paths = glob.glob(path)

# Debug: check if files are found
print(f"Files found: {len(file_paths)}")

if file_paths:
    df_list = [pd.read_csv(file) for file in file_paths]
    df = pd.concat(df_list, ignore_index=True)
else:
    print("No files found. Check your file path and extension.")

Files found: 12

C:\Users\aoket\AppData\Local\Temp\ipykernel_40444\3573284447.py:12: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = [pd.read_csv(file) for file in file_paths]

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob

In [17]:
file_paths = glob.glob("C:/Data Analytics/Bike/*.csv")
df_list = [pd.read_csv(file) for file in file_paths]
df = pd.concat(df_list, ignore_index=True)

C:\Users\aoket\AppData\Local\Temp\ipykernel_40444\377691089.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = [pd.read_csv(file) for file in file_paths]

In [18]:
bike_trips = df

In [19]:
bike_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5504784 entries, 0 to 5504783
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             object
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(3), object(10)
memory usage: 546.0+ MB

In [20]:
bike_trips.describe()

          start_lat     start_lng       end_lng
count  5.504784e+06  5.504784e+06  5.504783e+06
mean   4.190084e+01 -8.764618e+01 -8.764642e+01
std    4.651231e-02  2.917660e-02  2.942247e-02
min    4.164000e+01 -8.784000e+01 -8.897000e+01
25%    4.188132e+01 -8.766000e+01 -8.766027e+01
50%    4.189897e+01 -8.764182e+01 -8.764275e+01
75%    4.192914e+01 -8.762772e+01 -8.762775e+01
max    4.207000e+01 -8.752000e+01 -8.749000e+01

In [21]:
bike_trips.shape

(5504784, 13)

In [22]:
bike_trips.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

In [23]:
bike_trips.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BE796170FAFE24EB,classic_bike,2021-01-25 15:52,2021-01-26 15:16,Field Blvd & South Water St,15534,Unspecified dock station,Unknown,41.886349,-87.617517,41.88,-87.640000,member
1,2C9FB5EAAC0E39BE,docked_bike,2021-01-02 14:21,2021-01-03 13:45,Buckingham Fountain,15541,Kingsbury St & Kinzie St,KA1503000043,41.876511,-87.620548,41.889177,-87.638506,casual
2,D2BC3831A08FF1D6,docked_bike,2021-01-03 13:17,2021-01-05 12:25,Theater on the Lake,TA1308000001,Theater on the Lake,TA1308000001,41.926277,-87.630834,41.926277,-87.630834,casual
3,C4A4DEC5D5411299,classic_bike,2021-01-25 16:19,2021-01-26 15:16,Dearborn St & Monroe St,TA1305000006,Unspecified dock station,Unknown,41.881320,-87.629521,41.88,-87.640000,member
4,7BFBDD1F8590A02A,docked_bike,2021-01-09 16:23,2021-01-10 15:04,Wells St & Elm St,KA1504000135,Morgan St & Lake St,TA1306000015,41.903222,-87.634324,41.885483,-87.652305,casual

In [24]:
# Remove lat, long
# The 'errors="ignore"' argument prevents an error if a column is not found
bike_trips = bike_trips.drop(columns=['start_lat', 'start_lng', 'end_lat', 'end_lng'], errors='ignore')

In [25]:
bike_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5504784 entries, 0 to 5504783
Data columns (total 9 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   member_casual       object
dtypes: object(9)
memory usage: 378.0+ MB

In [26]:
# Convert 'started_at' and 'ended_at' to datetime objects
bike_trips['started_at'] = pd.to_datetime(bike_trips['started_at'])
bike_trips['ended_at'] = pd.to_datetime(bike_trips['ended_at'])

In [27]:
# Add columns that list the date, month, and day of each ride
bike_trips['date'] = bike_trips['started_at'].dt.date
bike_trips['month'] = bike_trips['started_at'].dt.month_name()
bike_trips['day'] = bike_trips['started_at'].dt.day
bike_trips['day_of_week'] = bike_trips['started_at'].dt.day_name()

In [28]:
# Add a "ride_length" calculation to all_trips (in seconds)
bike_trips['ride_length'] = (bike_trips['ended_at'] - bike_trips['started_at']).dt.total_seconds()

In [29]:
bike_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5504784 entries, 0 to 5504783
Data columns (total 14 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          datetime64[ns]
 3   ended_at            datetime64[ns]
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   member_casual       object
 9   date                object
 10  month               object
 11  day                 int32
 12  day_of_week         object
 13  ride_length         float64
dtypes: datetime64[ns](2), float64(1), int32(1), object(10)
memory usage: 567.0+ MB

In [30]:
bike_trips.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,date,month,day,day_of_week,ride_length
0,BE796170FAFE24EB,classic_bike,2021-01-25 15:52:00,2021-01-26 15:16:00,Field Blvd & South Water St,15534,Unspecified dock station,Unknown,member,2021-01-25,January,25,Monday,84240.0
1,2C9FB5EAAC0E39BE,docked_bike,2021-01-02 14:21:00,2021-01-03 13:45:00,Buckingham Fountain,15541,Kingsbury St & Kinzie St,KA1503000043,casual,2021-01-02,January,2,Saturday,84240.0
2,D2BC3831A08FF1D6,docked_bike,2021-01-03 13:17:00,2021-01-05 12:25:00,Theater on the Lake,TA1308000001,Theater on the Lake,TA1308000001,casual,2021-01-03,January,3,Sunday,169680.0
3,C4A4DEC5D5411299,classic_bike,2021-01-25 16:19:00,2021-01-26 15:16:00,Dearborn St & Monroe St,TA1305000006,Unspecified dock station,Unknown,member,2021-01-25,January,25,Monday,82620.0
4,7BFBDD1F8590A02A,docked_bike,2021-01-09 16:23:00,2021-01-10 15:04:00,Wells St & Elm St,KA1504000135,Morgan St & Lake St,TA1306000015,casual,2021-01-09,January,9,Saturday,81660.0

In [31]:
# Descriptive analysis on ride_length (all figures in seconds)
print("\nDescriptive statistics for ride_length:\n", bike_trips['ride_length'].describe())

Descriptive statistics for ride_length:
 count    5.504784e+06
mean     1.259289e+03
std      8.378561e+03
min      6.000000e+01
25%      4.200000e+02
50%      7.200000e+02
75%      1.320000e+03
max      3.235260e+06
Name: ride_length, dtype: float64

In [32]:
# Compare members and casual users
print("\nRide length statistics grouped by member_casual:\n", bike_trips.groupby('member_casual')['ride_length'].agg(['mean', 'median', 'max', 'min']))

Ride length statistics grouped by member_casual:
                       mean  median        max   min
member_casual
60               60.000000    60.0       60.0  60.0
casual         1797.385133   960.0  3235260.0  60.0
member          814.462879   600.0    90000.0  60.0

In [40]:
bike_trips.drop(bike_trips[bike_trips['member_casual'] == '60'].index, inplace=True)

In [41]:
print("\nRide length statistics grouped by member_casual:\n", bike_trips.groupby('member_casual')['ride_length'].agg(['mean', 'median', 'max', 'min']))

Ride length statistics grouped by member_casual:
                       mean  median        max   min
member_casual
casual         1797.385133   960.0  3235260.0  60.0
member          814.462879   600.0    90000.0  60.0

In [43]:
counts = bike_trips.groupby('member_casual')['ride_length'].agg(['mean', 'median', 'max', 'min']).reset_index()
counts.to_csv('Ride_Length_Statistics.csv', index=False)

In [54]:
# See the average ride time by each day for members vs casual riders
print("\nAverage ride length by member type and day of the week:\n", bike_trips.groupby(['member_casual', 'day_of_week'])['ride_length'].mean())

Average ride length by member type and day of the week:
 member_casual  day_of_week
casual         Friday         1678.119620
               Monday         1830.681335
               Saturday       1937.949020
               Sunday         2111.689376
               Thursday       1537.762855
               Tuesday        1599.117119
               Wednesday      1557.271755
member         Friday          795.951903
               Monday          789.132889
               Saturday        911.558103
               Sunday          931.866586
               Thursday        763.252959
               Tuesday         765.873028
               Wednesday       769.523061
Name: ride_length, dtype: float64

In [56]:
# Order the days of the week for correct sorting for analysis
days_order = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
bike_trips['day_of_week'] = pd.Categorical(bike_trips['day_of_week'], categories=days_order, ordered=True)

In [58]:
print("\nAverage ride length (sorted by day of week):\n", bike_trips.groupby(['member_casual', 'day_of_week'])['ride_length'].mean())

C:\Users\aoket\AppData\Local\Temp\ipykernel_40444\334641055.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print("\nAverage ride length (sorted by day of week):\n", bike_trips.groupby(['member_casual', 'day_of_week'])['ride_length'].mean())

Average ride length (sorted by day of week):
 member_casual  day_of_week
casual         Sunday         2111.689376
               Monday         1830.681335
               Tuesday        1599.117119
               Wednesday      1557.271755
               Thursday       1537.762855
               Friday         1678.119620
               Saturday       1937.949020
member         Sunday          931.866586
               Monday          789.132889
               Tuesday         765.873028
               Wednesday       769.523061
               Thursday        763.252959
               Friday          795.951903
               Saturday        911.558103
Name: ride_length, dtype: float64

In [60]:
counts = bike_trips.groupby(['member_casual', 'day_of_week'])['ride_length'].mean().reset_index()
counts.to_csv('Average_ride_length.csv', index=False)

C:\Users\aoket\AppData\Local\Temp\ipykernel_40444\1978650173.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = bike_trips.groupby(['member_casual', 'day_of_week'])['ride_length'].mean().reset_index()

In [62]:
# Analyze rider ride length and number of rides data by type and weekday
summary_stats = bike_trips.groupby(['member_casual', 'day_of_week']).agg(number_of_rides=('ride_id', 'count'),
    average_duration=('ride_length', 'mean')).reset_index().round(2)

C:\Users\aoket\AppData\Local\Temp\ipykernel_40444\3559003019.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary_stats = bike_trips.groupby(['member_casual', 'day_of_week']).agg(number_of_rides=('ride_id', 'count'),

In [63]:
print("\nSummary of rides and duration by rider type and weekday:\n", summary_stats)

Summary of rides and duration by rider type and weekday:
    member_casual day_of_week  number_of_rides  average_duration
0         casual      Sunday           473743           2111.69
1         casual      Monday           282152           1830.68
2         casual     Tuesday           270365           1599.12
3         casual   Wednesday           274836           1557.27
4         casual    Thursday           281904           1537.76
5         casual      Friday           358587           1678.12
6         casual    Saturday           549630           1937.95
7         member      Sunday           369016            931.87
8         member      Monday           409152            789.13
9         member     Tuesday           457975            765.87
10        member   Wednesday           469431            769.52
11        member    Thursday           444254            763.25
12        member      Friday           438779            795.95
13        member    Saturday           424959            911.56

In [64]:
counts = bike_trips.groupby(['member_casual', 'day_of_week']).agg(number_of_rides=('ride_id', 'count'),
    average_duration=('ride_length', 'mean')).reset_index().round(2)
counts.to_csv('Daily_Ride_Summary.csv', index=False)

C:\Users\aoket\AppData\Local\Temp\ipykernel_40444\2921858807.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = bike_trips.groupby(['member_casual', 'day_of_week']).agg(number_of_rides=('ride_id', 'count'),

In [65]:
summary_stats2 = bike_trips.groupby(['member_casual', 'month']).agg(number_of_rides=('ride_id', 'count'),
    average_duration=('ride_length', 'mean')).reset_index().round(2)

In [6]:
print("\nSummary of rides and duration by rider type and month:\n", summary_stats2)

NameError: name 'summary_stats2' is not defined

In [67]:
counts = bike_trips.groupby(['member_casual', 'month']).agg(number_of_rides=('ride_id', 'count'),
    average_duration=('ride_length', 'mean')).reset_index().round(2)
counts.to_csv('Monthly_ride_Summary.csv', index=False)

In [68]:
bike_trips['start_ride_hour'] = bike_trips['started_at'].dt.hour

In [69]:
bike_trips.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5504783 entries, 0 to 5504783
Data columns (total 15 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          datetime64[ns]
 3   ended_at            datetime64[ns]
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   member_casual       object
 9   date                object
 10  month               object
 11  day                 int32
 12  day_of_week         category
 13  ride_length         float64
 14  start_ride_hour     int32
dtypes: category(1), datetime64[ns](2), float64(1), int32(2), object(9)
memory usage: 593.2+ MB

In [70]:
summary_stats3 = bike_trips.groupby(['member_casual', 'start_ride_hour']).agg(number_of_rides=('ride_id', 'count'),
    average_duration=('ride_length', 'mean')).reset_index().round(2)

In [74]:
print("\nSummary of rides and duration by rider type and start of ride hour:\n", summary_stats3)

Summary of rides and duration by rider type and start of ride hour:
    member_casual  start_ride_hour  number_of_rides  average_duration
0         casual                0            52968           1859.51
1         casual                1            38542           1916.67
2         casual                2            25077           2106.15
3         casual                3            13818           2320.02
4         casual                4             9761           1871.02
5         casual                5            12329           1281.95
6         casual                6            25373           1193.50
7         casual                7            46114           1219.43
8         casual                8            62725           1370.75
9         casual                9            75102           1656.28
10        casual               10           103185           1913.49
11        casual               11           133952           1941.10
12        casual               12           159596           1934.08
13        casual               13           170826           1958.02
14        casual               14           175822           2016.20
15        casual               15           185829           1933.87
16        casual               16           202343           1779.13
17        casual               17           233293           1667.71
18        casual               18           210701           1689.02
19        casual               19           163810           1684.59
20        casual               20           120202           1791.06
21        casual               21           102196           1757.03
22        casual               22            94753           1776.99
23        casual               23            72900           1795.57
24        member                0            32462            794.94
25        member                1            21422            862.96
26        member                2            12170            855.96
27        member                3             7013            859.81
28        member                4             7997            777.97
29        member                5            29581            700.26
30        member                6            80612            732.74
31        member                7           147561            739.43
32        member                8           170595            731.07
33        member                9           128714            755.67
34        member               10           127037            808.84
35        member               11           152708            819.94
36        member               12           177549            804.36
37        member               13           174707            819.28
38        member               14           171506            847.07
39        member               15           197539            843.13
40        member               16           253205            845.79
41        member               17           314966            855.53
42        member               18           266901            844.61
43        member               19           190951            830.84
44        member               20           129162            822.73
45        member               21            95391            804.08
46        member               22            73177            812.88
47        member               23            50640            804.00

In [72]:
counts = bike_trips.groupby(['member_casual', 'start_ride_hour']).agg(number_of_rides=('ride_id', 'count'),
    average_duration=('ride_length', 'mean')).reset_index().round(2)
counts.to_csv('Hour_ride_Statistics.csv', index=False)

In [73]:
summary_stats4 = bike_trips.groupby(['member_casual', 'rideable_type']).agg(number_of_rides=('ride_id', 'count'))

In [75]:
print("\nSummary of rideable type and users:\n", summary_stats4)

Summary of rideable type and users:
                              number_of_rides
member_casual rideable_type
casual        classic_bike           1250178
              docked_bike             309971
              electric_bike           931068
member        classic_bike           1954345
              docked_bike                  1
              electric_bike          1059220

In [77]:
counts = bike_trips.groupby(['member_casual', 'rideable_type']).agg(number_of_rides=('ride_id', 'count')).reset_index()
counts.to_csv('Rideable_Type.csv', index=False)

In [78]:
summary_stats5 = bike_trips.groupby(['member_casual']).agg(number_of_rides=('ride_id', 'count'),
    average_duration=('ride_length', 'mean')).reset_index().round(2)

In [79]:
print("\nSummary of Riders numbers of ride and average ride length:\n", summary_stats5)

Summary of Riders numbers of ride and average ride length:
   member_casual  number_of_rides  average_duration
0        casual          2491217           1797.39
1        member          3013566            814.46

In [80]:
counts = bike_trips.groupby(['member_casual']).agg(number_of_rides=('ride_id', 'count'),
    average_duration=('ride_length', 'mean')).reset_index().round(2)
counts.to_csv('Total Ride Statistics.csv', index=False)

In [7]:
import pandas as pd